name: CI with Cache

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout code từ repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Bước 2: Thiết lập bộ nhớ đệm
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            vendor/bundle
          key: ${{ runner.os }}-deps-${{ hashFiles('**/package-lock.json', '**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      # Bước 3: Cài đặt dependencies (ví dụ cho Node.js)
      - name: Install Node.js dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm install

      # Bước 4: Chạy tests (ví dụ)
      - name: Run tests
        run: npm test
